### ISSUE TITLE
Minimum viable website checklist

### ISSUE THREAD

**Issue by AlexVipond** [jennifervipond/vipondforcongress#1]
### Design
- [ ] Color scheme
- [ ] Decent logo
- [ ] Typography
- [ ] hi-res photos of JV
- [ ] Appropriate whitespace

### Functionality
- [ ] Mobile responsive
- [ ] Donate button
- [ ] Email list signup form
- [ ] Contact form
- [ ] Published with custom domain on GitHub Pages

### Content
- [ ] About page
- [ ] Broad position statements on home page
