### ISSUE TITLE
Nice-to-have digital marketing checklist

### ISSUE THREAD

**Issue by AlexVipond** [jennifervipond/vipondforcongress#2]
### Design
- [ ] Second pair of eyes on website
- [ ] Improved logo

### Functionality
- [ ] Support for older browsers
- [ ] Stripe for accepting donations
- [ ] Mail for Good email signup

### Content
- [ ] Active Twitter account
- [ ] Hi-res video interview
- [ ] Detailed policy positions, 500-1,000 words
